// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Database.Data;
using api.Utils.Helper;
using static api.Utils.Helper.Enum;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240608213321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.BiodataMigration", b =>
            {
            b.Property<string>("NIK")
                .HasColumnType("nvarchar(450)");

            b.Property<string>("agama")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("alamat")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("golongan_darah")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<KelaminEnum>("jenis_kelamin")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("kewarganegaraan")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("nama")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("pekerjaan")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<status_perkawinanEnum>("status_perkawinan")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("tanggal_lahir")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("tempat_lahir")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.HasKey("NIK");

            b.ToTable("biodata");
            });

            modelBuilder.Entity("api.Models.SidikJariMigration", b =>
            {
                b.Property<string>("berkas_citra")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("nama")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("berkas_citra");

                b.ToTable("sidik_jari");
            });
#pragma warning restore 612, 618
        }
    }
}

